### ISSUE TITLE
"Status 500: Unexpected Problem" when accessing grid's forecast

### ISSUE THREAD

**Issue by ChaseBosman** [weather-gov/api#160]
**Describe the bug**
Occasionally when accessing a grid's weather forecast, a status 500 error is returned. The error message indicates that an unexpected problem has occurred.

**To Reproduce**
The link currently providing this error is: https://api.weather.gov/gridpoints/MTR/114,128

**If possible, also include the correlationId from the response**
1dc193d9

**Expected behavior**
The expected JSON response for a grid's forecast.

**Screenshots**
![image](https://user-images.githubusercontent.com/54570221/106550866-daadeb80-64c8-11eb-9e3b-b4da4aa1b8b9.png)

**Additional Context**
I have noticed that this is a rather intermittent issue.

Thanks,
Chase

**Comment by iampeterdaniels** [comment]
I've noticed this, too. I added retry looping with exponential backoff to my code. Usually the second or third GET will succeed.

**Comment by ChaseBosman** [comment]
It's interesting...revisiting this problem 12 days later, the same grid is still producing the error.

**Comment by whoinow** [comment]
I am also getting this problem even with 3 retries 1s apart. I am going to try backing off my retries, but I doubt that will help. I will say I am hitting a different endpoint though: https://api.weather.gov/gridpoints/MTR/83,153/forecast/hourly

**Comment by scadergit** [comment]
Status 500 errors are operational outages and can be reported to the helpdesk for a more immediate response. The original request has been purged from the logs, so I can no longer determinen the cause. If anyone can provide a more recent correlation id then I will look into it.

**Comment by whoinow** [comment]
Unfortunately my logging doesn't have a correlationId. I make my requests at 12am PST. Are their planned outages at certain times? I looked [here](https://www.weather.gov/notification/) and didn't see anything.

**Comment by ChaseBosman** [comment]
> Status 500 errors are operational outages and can be reported to the helpdesk for a more immediate response. The original request has been purged from the logs, so I can no longer determinen the cause. If anyone can provide a more recent correlation id then I will look into it. 

Here is a recently generated correlation ID for the issue: 4a3c06e7

The link in the original post for this issue actually always generates this error for me, which is interesting seeing that the grid is a fairly large city in California.
