### ISSUE TITLE
Gridpoints API current conditions

### ISSUE THREAD

**Issue by mrgatesjunior** [weather-gov/api#174]
I like the gridpoints API in general and like also the hourly function.  However, unless I am missing something, neither provide current conditions.  Meaning current temperature, wind speed, etc.

How does one even pull current conditions with the gridpoints API approach ?

**Comment by netbymatt** [comment]
It's a few steps. First get a list of stations such as
https://api.weather.gov/gridpoints/LOT/52,80/stations
The list seems to be sorted with the closest station first.
Once you grab the station URL, get the latest observations such as:
https://api.weather.gov/stations/KDPA/observations/latest

**Comment by mrgatesjunior** [comment]
> It's a few steps. First get a list of stations such as
> https://api.weather.gov/gridpoints/LOT/52,80/stations
> The list seems to be sorted with the closest station first.
> Once you grab the station URL, get the latest observations such as:
> https://api.weather.gov/stations/KDPA/observations/latest

Yeah, I figured that out.  However, it would be nice to be able to pull everything from one call through the gridpoints API.

**Comment by scadergit** [comment]
The API is currently designed out of necessity for efficiency and performance. Future environment improvements might allow graphql or other convienences.
