### ISSUE TITLE
Starting 3-4 months ago, getting old forecast (cache issue?)

### ISSUE THREAD

**Issue by engpok** [weather-gov/api#177]
I’ve been accessing weather.gov api for more than 5 years. I have been using my own Labview app which uses a “curl” command to request a weather forecast. I request the forecast once an hour. In the past 3-4 months I’ve discovered that many times I get a day old or sometimes two day old forecast. I’m using the following command (from Labview 2011, on MacOS 10.14.6):

curl https://api.weather.gov/gridpoints/LWX/79,75
User-Agent: personal/Labview 2011 (Internal Application, EngPokrass@gmail.com)

I’m suspecting that cacheing is the issue, but every time I use the same address on Chrome’s browser, I always get the current forecast.

Any idea what I might be doing wrong?

Thanks, in advance

**Comment by scadergit** [comment]
Will you provide the correlation id for a request that returns a forecast that is old? That will help us determine if the cached reply came from the CDN or origin.

**Comment by engpok** [comment]
Thanks Jared,

OK, I had to do some research into these new terms of “correlation ID” and “CDN”. I added the “verbose” option to my curl command, and I have the following example:

 - curl command sent on 17 Mar, 0730 eastern time

 - forecast data shows 15 Mar:
    "properties": {
        ***@***.***": "https://api.weather.gov/gridpoints/LWX/79,75",
        ***@***.***": "wx:Gridpoint",
        "updateTime": "2021-03-15T11:35:36+00:00",
        "validTimes": "2021-03-15T05:00:00+00:00/P7DT20H",

 - correlation ID:
.
.
.
Administration; CN=weather.gov
*  start date: Sep 18 00:00:00 2020 GMT
*  expire date: Oct 18 12:00:00 2021 GMT
.
.
.
< x-request-id: c49de7b8-c895-4d42-be3e-1539858ad0e1
< x-correlation-id: 1085dc59
< x-server-id: vm-bldr-nids-apiapp5.ncep.noaa.gov
< cache-control: public, max-age=900, s-maxage=3600
< expires: Wed, 17 Mar 2021 12:01:27 GMT
< date: Wed, 17 Mar 2021 11:46:27 GMT


Hmmmmm… is this maybe considered a valid forecast since the “validTimes” covers 17 Mar, 0730?

**Comment by engpok** [comment]
Hi Jared, have you found any clues?
