### ISSUE TITLE
How do I get sky cover (%) for weather observations?

### ISSUE THREAD

**Issue by sthapa123** [weather-gov/api#180]
Using the weather gov api, I get the sky cover in percentage for weather forecast. However, I get the weather observations in values like FEW, BKN, SCT, etc. Is there any way to convert these values to sky cover percentage? I'd be very grateful if you could help me on this.

**Comment by hluker** [comment]
@sthapa123,
There isn't a direct/specific percentage for the weather observations. The METARs will provide cloud cover in either FEW (1/8 to 2/8 cloud coverage), SCT (scattered, 3/8 to 4/8 cloud coverage, BKN (broken, 5/8-7/8 coverage), and OVC (overcast, 8/8 coverage), along with their respective heights.
