### ISSUE TITLE
Marine Forecast

### ISSUE THREAD

**Issue by carlosga01** [weather-gov/api#184]
Hello, I have been scouring the API documentation for an endpoint to retrieve marine forecasts (wave height, wind direction, wind gusts, etc), but have not found any. Every forecast endpoint seems to not support marine requests. Are the marine forecasts not available on the public API? Or have I missed something?

**Comment by scadergit** [comment]
The API does not support marine forecast, but we're working with the OPC to provide that soon (probably late spring/summer).

**Comment by carlosga01** [comment]
Thanks for the quick response! Sounds good
