### ISSUE TITLE
Hourly forecast should include relative humidity

### ISSUE THREAD

**Issue by brewin** [weather-gov/api#32]
The /forecast/hourly endpoint doesn't currently include relative humidity. It's impossible to calculate a heat index without it. The old hourly forecast API does include it.

**Comment by scadergit** [comment]
Sorry for the delayed reply. This appears to be an oversight. We'll determine when it can be added back in, but that might take longer than expected due to proceses outside of our control. As noted elsewhere, the forecast endpoints are not heavily prioroitized at this time.

**Comment by dmeinrath** [comment]
any update on this?

**Comment by scadergit** [comment]
Sorry, only more of this:
> that might take longer than expected due to proceses outside of our control.
