### ISSUE TITLE
Current observation fields are all zero

### ISSUE THREAD

**Issue by at1993** [weather-gov/api#61]
Hi Guys,

Sometime the response returned with current observation fields are set to zero. 
Is there a work around or is it simply data is not available at that time?

> `<data type="current observations">
        <location>
            <location-key>point1</location-key>
            <point latitude="21.3275" longitude="-157.94306"/>
            <area-description>Honolulu, Honolulu International Airport, HI</area-description>
            <height datum="mean sea level" height-units="feet">10</height>
        </location>
        <moreWeatherInformation applicable-location="point1">https://forecast.weather.gov/obs/PHNL/history</moreWeatherInformation>
        <time-layout time-coordinate="local">
            <layout-key>k-p1h-n1-1</layout-key>
            <start-valid-time period-name="current">2020-05-29T12:53:00+00:00</start-valid-time>
        </time-layout>
        <parameters applicable-location="point1">
            <temperature type="apparent" units="Fahrenheit" time-layout="k-p1h-n1-1">
                <value>0</value>
            </temperature>
            <temperature type="dew point" units="Fahrenheit" time-layout="k-p1h-n1-1">
                <value>0</value>
            </temperature>
            <humidity type="relative" time-layout="k-p1h-n1-1">
                <value>0</value>
            </humidity>
            <weather time-layout="k-p1h-n1-1">
                <name>Weather Type, Coverage, Intensity</name>
                <weather-conditions weather-summary="Mostly Clear"/>
                <weather-conditions>
                    <value>
                        <visibility units="statute miles">10</visibility>
                    </value>
                </weather-conditions>
            </weather>
            <conditions-icon type="forecast-NWS" time-layout="k-p1h-n1-1">
                <name>Conditions Icon</name>
                <icon-link>https://api.weather.gov/icons/land/night/few?size=medium</icon-link>
            </conditions-icon>
            <direction type="wind" units="degrees true" time-layout="k-p1h-n1-1">
                <value>0</value>
            </direction>
            <wind-speed type="gust" units="knots" time-layout="k-p1h-n1-1">
                <value>0</value>
            </wind-speed>
            <wind-speed type="sustained" units="knots" time-layout="k-p1h-n1-1">
                <value>0</value>
            </wind-speed>
            <pressure type="barometer" units="inches of mercury" time-layout="k-p1h-n1-1">
                <value>0</value>
            </pressure>
        </parameters>
    </data>`

**Comment by webdog** [comment]
I have a similar problem. When I request /observations/latest, the `properties.periods` key will sometimes not exist in the payload (I use this data to save forecast data for the next day). As an example, my application was parsing this key up until about 30 minutes ago, and now it has disappeared. It appears to be based on the time of day, but not sure.

I've made my application stateless, but I think I might have to start saving the data when it's fetchable, as it doesn't seem the API is guaranteeing its delivery.
